"""Add podcast table and migrate episode FK

Revision ID: 0e6cd81255d8
Revises: f981d91c9652
Create Date: 2026-01-16 13:19:41.776523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e6cd81255d8"
down_revision: Union[str, Sequence[str], None] = "f981d91c9652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Create podcasts table
    op.create_table(
        "podcasts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("feed_url", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )

    # Step 2: Seed existing podcasts
    op.execute(
        """
        INSERT INTO podcasts (name, slug, feed_url)
        VALUES
            ('Le rendez-vous Tech', 'rdv-tech', 'https://feedpress.me/rdvtech'),
            ('Le rendez-vous Jeux', 'rdv-jeux', 'https://feeds.acast.com/public/shows/le-rendez-vous-jeux'),
            ('The Phileas Club', 'phileas-club', 'https://feedpress.me/thephileasclub')
        """
    )

    # Step 3: Add podcast_id column (nullable initially for data migration)
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("podcast_id", sa.Integer(), nullable=True))

    # Step 4: Populate podcast_id from existing podcast string
    op.execute(
        """
        UPDATE episodes
        SET podcast_id = (
            SELECT id FROM podcasts WHERE podcasts.name = episodes.podcast
        )
        """
    )

    # Step 5: Make podcast_id NOT NULL and add FK, then drop old column
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.alter_column("podcast_id", nullable=False)
        batch_op.create_foreign_key(
            "fk_episodes_podcast_id", "podcasts", ["podcast_id"], ["id"]
        )
        batch_op.drop_column("podcast")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add podcast string column back (nullable initially)
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("podcast", sa.VARCHAR(), nullable=True))

    # Step 2: Populate podcast from FK relationship
    op.execute(
        """
        UPDATE episodes
        SET podcast = (
            SELECT name FROM podcasts WHERE podcasts.id = episodes.podcast_id
        )
        """
    )

    # Step 3: Make podcast NOT NULL, drop FK and podcast_id
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.alter_column("podcast", nullable=False)
        batch_op.drop_constraint("fk_episodes_podcast_id", type_="foreignkey")
        batch_op.drop_column("podcast_id")

    # Step 4: Drop podcasts table
    op.drop_table("podcasts")
    # ### end Alembic commands ###
