"""Added episode summary field

Revision ID: 3975fa47cd25
Revises: 90dfcd298097
Create Date: 2026-01-09 16:45:23.516339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3975fa47cd25"
down_revision: Union[str, Sequence[str], None] = "90dfcd298097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
