"""Created episode table

Revision ID: 8d355058ddb4
Revises: ae80423cfac5
Create Date: 2025-12-09 17:05:11.611638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d355058ddb4'
down_revision: Union[str, Sequence[str], None] = 'ae80423cfac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_guid', 'episodes', ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_guid', 'episodes', type_='unique')
    # ### end Alembic commands ###
