"""Postgresql podcast database init

Revision ID: 90dfcd298097
Revises:
Create Date: 2026-01-05 14:59:04.071041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90dfcd298097"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Create the `episodes` table to initialize the podcast episodes schema.
    
    The table includes `uuid` as the primary key and columns for `podcast`, `episode_id`, `title`, `description`, `published_date`, `audio_url`, a `processing_stage` enum (`SYNCED`, `AUDIO_DOWNLOADED`, `RAW_TRANSCRIPT`, `FORMATTED_TRANSCRIPT`, `EMBEDDED`), optional file path columns (`audio_file_path`, `raw_transcript_path`, `speaker_mapping_path`, `formatted_transcript_path`), transcript metadata (`transcript_duration`, `transcript_confidence`), and timestamp columns `created_at` and `updated_at` defaulting to `now()`.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("podcast", sa.String(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published_date", sa.DateTime(), nullable=False),
        sa.Column("audio_url", sa.String(), nullable=False),
        sa.Column(
            "processing_stage",
            sa.Enum(
                "SYNCED",
                "AUDIO_DOWNLOADED",
                "RAW_TRANSCRIPT",
                "FORMATTED_TRANSCRIPT",
                "EMBEDDED",
                name="processingstage",
            ),
            nullable=False,
        ),
        sa.Column("audio_file_path", sa.String(), nullable=True),
        sa.Column("raw_transcript_path", sa.String(), nullable=True),
        sa.Column("speaker_mapping_path", sa.String(), nullable=True),
        sa.Column("formatted_transcript_path", sa.String(), nullable=True),
        sa.Column("transcript_duration", sa.Integer(), nullable=True),
        sa.Column("transcript_confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("episodes")
    # ### end Alembic commands ###