"""add podcast column to episodes table

Revision ID: a9a30fc4dad6
Revises: 8d355058ddb4
Create Date: 2025-12-22 14:10:21.551249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9a30fc4dad6"
down_revision: Union[str, Sequence[str], None] = "8d355058ddb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Add a non-nullable string column "podcast" with server default "unknown" to the "episodes" table.
    
    This migration updates the schema to include the "podcast" column; existing rows are populated using the server default "unknown".
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episodes",
        sa.Column("podcast", sa.String(), nullable=False, server_default="unknown"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Remove the "podcast" column from the "episodes" table.
    
    Reverts the schema change that added the non-nullable "podcast" column (with server default "unknown").
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episodes", "podcast")
    # ### end Alembic commands ###