"""Initial schema with episodes table

Revision ID: ae80423cfac5
Revises:
Create Date: 2025-12-09 17:01:18.385222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae80423cfac5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published_date", sa.DateTime(), nullable=False),
        sa.Column("audio_url", sa.String(), nullable=False),
        sa.Column(
            "processing_stage",
            sa.Enum(
                "SYNCED",
                "AUDIO_DOWNLOADED",
                "RAW_TRANSCRIPT",
                "FORMATTED_TRANSCRIPT",
                "EMBEDDED",
                name="processingstage",
            ),
            server_default="synced",
            nullable=False,
        ),
        sa.Column("audio_file_path", sa.String(), nullable=True),
        sa.Column("raw_transcript_path", sa.String(), nullable=True),
        sa.Column("speaker_mapping_path", sa.String(), nullable=True),
        sa.Column("formatted_transcript_path", sa.String(), nullable=True),
        sa.Column("transcript_duration", sa.Integer(), nullable=True),
        sa.Column("transcript_confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid"),
        sa.UniqueConstraint("guid", name="uq_guid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("episodes")
    # ### end Alembic commands ###
