"""Renamed summary col to summary_path

Revision ID: f981d91c9652
Revises: 3975fa47cd25
Create Date: 2026-01-12 11:36:24.991841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f981d91c9652"
down_revision: Union[str, Sequence[str], None] = "3975fa47cd25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary_path", sa.Text(), nullable=True))
        batch_op.drop_column("summary")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("summary_path")

    # ### end Alembic commands ###
